language: node_js
os: linux
dist: trusty
addons:
  apt:
    packages:
      # This is required to run new chrome on old trusty
      - libnss3
notifications:
  email: false
cache:
  directories:
    - node_modules
jobs:
  include:
    - node_js: "12.16.1"
      dist: trusty
      env:
        - CHROMIUM=true
      before_install: ./travis/setup-linux.sh
      script: ./travis/chromium.sh
    - node_js: "10.18.1"
      dist: trusty
      env:
        - CHROMIUM=true
      script: ./travis/chromium.sh
    - node_js: "10.18.1"
      os: windows
      before_install: ./travis/setup-linux.sh
      script: ./travis/chromium.sh
    - node_js: "10.18.1"
      os: windows
      script: 'npx eslint .'
      env:
        - CHROMIUM=true
    - node_js: "10.18.1"
      dist: trusty
      before_install: ./travis/setup-linux.sh
      script: 'if [ "$FIREFOX" = "true" ]; then BINARY=$FIREFOX_HOME/firefox/firefox npm run funit; fi'
      env:
        - FIREFOX=true
        - FIREFOX_HOME=$TRAVIS_HOME/firefox-latest
